### ISSUE TITLE
数据集请教

### ISSUE THREAD

**Issue by RyanCCC** [bubbliiiing/unet-keras#2]
博主，我是直接用labelme标注好的自己数据集进行训练，还是需要转换成灰度图，用0，1，2，3进行类别标注这样的标签数据？

**Comment by abrunchof** [comment]
前者吧？博主那个转换成灰度级值0和255的是本来也就对应于医学图像本身两种类别的颜色。RGB图像也不能单单靠灰度值不同分类。我也不知道我理解的对不对...

另外想插楼请教一下博主，我用自己的数据集训练，最终预测的图像有办法得到各个类别的边缘点位置吗？比如说检测狗，可以得到狗狗最外圈的轮廓点的坐标吗

**Comment by abrunchof** [comment]
> 博主，我是直接用labelme标注好的自己数据集进行训练，还是需要转换成灰度图，用0，1，2，3进行类别标注这样的标签数据？

前者吧？博主那个转换成灰度级值0和255的是本来也就对应于医学图像本身两种类别的颜色。RGB图像也不能单单靠灰度值不同分类。我也不知道我理解的对不对...

另外想插楼请教一下博主，我用自己的数据集训练，最终预测的图像有办法得到各个类别的边缘点位置吗？比如说检测狗，可以得到狗狗最外圈的轮廓点的坐标吗

**Comment by RyanCCC** [comment]
> > 博主，我是直接用labelme标注好的自己数据集进行训练，还是需要转换成灰度图，用0，1，2，3进行类别标注这样的标签数据？
> 
> 前者吧？博主那个转换成灰度级值0和255的是本来也就对应于医学图像本身两种类别的颜色。RGB图像也不能单单靠灰度值不同分类。我也不知道我理解的对不对...
> 
> 另外想插楼请教一下博主，我用自己的数据集训练，最终预测的图像有办法得到各个类别的边缘点位置吗？比如说检测狗，可以得到狗狗最外圈的轮廓点的坐标吗
前者也是单通道图，只是调色板或者灰度图的区别。我看了一些语义分割的也是用灰度图的，用0,1,2,3表示类别。

**Comment by bubbliiiing** [comment]
1、你正常标注，按步骤用labelme转换就行了，和医学没关系
2、
img = cv2.cvtColor(image2,cv2.COLOR_BGR2GRAY)

canny_img_one = cv2.Canny(img,300,150)

canny_img_two = canny_img_one.copy() # 复制图片

for i in range(0,canny_img_one.shape[0]): #image.shape表示图像的尺寸和通道信息(高,宽,通道)

for j in range(0,canny_img_one.shape[1]):

canny_img_two[i,j]= 255 - canny_img_one[i,j]

cv2.imshow('edge',canny_img_two)
用canny处理那个类的层

**Comment by RyanCCC** [comment]
已经解决

**Comment by bubbliiiing** [comment]
好的加油
