### ISSUE TITLE
训练震荡问题请教

### ISSUE THREAD

**Issue by RyanCCC** [bubbliiiing/unet-keras#3]
你好，我在训练过程中fscore时而高时而低，有点震荡，请问你有遇到过吗？谢谢！
![微信截图_20210602143216](https://user-images.githubusercontent.com/27406337/120435635-8f411680-c3b0-11eb-9418-5b72eba64850.png)

**Comment by bubbliiiing** [comment]
正常，数据集偏少

**Comment by RyanCCC** [comment]
> 正常，数据集偏少
感觉好像到达了瓶颈

**Comment by bubbliiiing** [comment]
什么瓶颈
